### PR TITLE
Provide pre-configured IDE projects

### PR DESCRIPTION
**Pull request by languitar**
This pull requests adds pre-configured projects for Eclipse, Netbeans and IntelliJ as well as the astyle formatter to the code base. The rationale is that we can enforce consistent coding conventions much better when people can clone the repo and immediately get an IDE configuration that matches the desired code style and includes the required reporting plugins (ie. checkstyle and PMD). Instructions on how to use all of these projects have been added to the `README.markdown` file.

For the IntelliJ IDEA project someone who is using this IDE (@cobratbq ?) should ideally have a look at it once before merging, since I am not a regular user of that IDE and I might have missed some bits and pieces.

It is also worth noting that astyle produces some really strange things when formatting java which simply cannot be configured (e.g. no indentation when wrapping throws statements to the next line). So while it would be generally desirable to have an IDE-independent formatter as a baseline, this isn't possible with astyle at the moment (at least if the source code should following understandable conventions). I have included the configuration anyway since it might help someone to get closer to something usable in less time then performing all cleanup manually.

Apart from the actual IDE configuration I have also included a few fixes to the checkstyle configuration which I discovered while preparing the IDE projects.

### CODE REVIEW

**Comment by cobratbq** [comment]
I don't use (or ever have used) IntelliJ IDEA. So someone else should check that configuration. I can have a look at Netbeans and Eclipse configurations.

**Comment by languitar** [comment]
Oh ok, I thought I read something about that somewhere here. For Eclipse I am quite sure since I use such a configuration since years at work.

**Comment by eighthave** [comment]
I'm fine with including the `.classpath` and `.project` files, but I have had issues committing anything in `.settings/`.  I think committing Eclipse's `.settings/` only works on projects where all the developers are in agreement to do that, and are used to working with `.settings/` in git.

**Comment by eighthave** [comment]
I should add, I set up the Android code formatter in the workspace, rather than per-project.  So that's one place where those prefs stored `.settings/` would cause conflicts.

**Comment by languitar** [comment]
Not including the project settings completely contradicts the intentions of having pre-configured projects so that people can easily start developing and consistent options are available. Everything from the checkstyle plugin to the code formatter is defined in the settings files. These settings override workspace-wide settings for the project. So there is no conflict with your android formatter being configured for the whole workspace. For the otr4j project there will simply be the one used contained in the project, which coincidentally should be the same as the one in the workspace. Moreover, settings are completely decoupled from the user environment with maven-based projects and settings files even transfer well across different eclipse and plugin versions. Any personal preferences regarding the editor setup, shortcuts etc. are of course not included in the .settings files.

We are using such setups since years and never had problems with this approach. On the contrary, I have seen may situations where this helped to maintain coding style and code quality due to the immediately available feedback.

Which problems do you see with this approach?

**Comment by eighthave** [comment]
Having the custom checkstyle included in the project settings will likely conflict with the Android formatter set up in either the workspace or the project.  Right now, we've only really talked about the Android formatter as the canonical code format, and its also not really decided yet since we really need the jitsi people to weigh in this before committing to a given code style.

As for conflicts I've seen, once the .settings/ folder is included, then often people mistakenly commit their own changes to git, and also if someone does customize their settings, they will have to manage any conflicts in that folder, and Eclipse makes that very difficult.  Having .project and .classpath included makes it quick to get going building the project, and there are rarely conflicts there.

**Comment by languitar** [comment]
Checkstyle does not influence the code formatting in any way. The plugin just reports warnings just like the maven report does, but inline in the editor. Same is true for the PMD plugin. They just provide inline annotations. And in case we decide on a different format, the settings can of course be adapted.

In order to prevent undesired commits in the settings folder we can just add that one to the gitignore file again, but still include it in the repository.

Just having a .project and .classpath file is completely useless. This part is already managed by maven and doesn't provide any benefit. The important aspect is about using the editing features in the IDEs to support maintaining the external code quality without effort for contributors. And this is only possible with configured projects including the required settings.

**Comment by cobratbq** [comment]
I don't believe checkstyle or PMD would cause trouble either. These are just settings being loaded in a plugin that puts some annotations in the editor for "dubious" content.

About the .settings directory (or IDE configuration files in general) ... I actually don't know which side to pick :-P. I understand @eighthave position on not committing IDE configuration. And this is "redundant" in a sense, since we also have maven pom.xml outlining the project's configuration. **However**, it is **really** convenient not to have to set up a whole development environment when you just want to make small change.

@languitar are there any possibilities of providing an importable configuration file? I mean maybe something like an export of a fully configured IDE that you then import for your project and _Done_ with your configuration. That would be both:
1. convenient
2. quick
3. virtually 0 risk of accidentally overwriting in a commit
4. we can still ignore "raw IDE configuration" files

Just thinking out loud. Not sure if this is feasible ...

**Comment by cobratbq** [comment]
Just checked. Both Eclipse and Netbeans support some sort of saving IDE configuration. I'm going to look into this at a later moment, as I am still interested in having a predefined IDE configuration available.

**Comment by languitar** [comment]
I did't have much time, but what could be possible in any case would be to provide a zip or something like that which should be extracted into the source tree.

**Comment by cobratbq** [comment]
I'd like to revisit this topic later. Let's see this become an issue first. The reason I don't want to tackle it now, is that I fear these set-ups become outdated too quickly and therefore are a bother to maintain.

**Pull request closed without merging**
