### PR TITLE
Test infrastructure for OTR negotiation

### PR DESCRIPTION
**Pull request by eighthave**
Prompted by the recent bug fixed in #6, I wanted to be able to test parse of the OTR messaging itself, rather than just an overview.  These series of commits make it possible to stop `DummyClient`'s OTR negotiation midway, then probe and run things to make sure they are working properly.  This test would have detected the issue of #6, but it should be expanded to test each step of the OTR negotiation.

Also, this starts the process of removing the `Impl` classes with the matched `abstract` classes, since they are just clutter and make testing those classes a lot more difficult.  I chatted with @gpolitis on  irc://irc.freenode/net/jitsi about it, here's the summary:

@eighthave: I don't understand why things like `AuthContex` and `AuthContextImpl` are separate classes?  They seem like they should just be a single class since `AuthContextImpl` is the only implementation of `AuthContext`.  And having them split up like that makes it hard to write tests for things like that most recent bug/pull request
@gpolitis: you're absolutely right. If I were to code it again, I'd definitely remove many of the interfaces and keep the implementations only.

### CODE REVIEW

**Comment by devrandom** [comment]
It looks like the whitespace handling in your editor is different from what the code currently uses.

**Comment by eighthave** [comment]
I couldn't figure out what whitespace and code format otr4j uses.  It seems some parts of it wraps at 80 chars, other parts wraps at 100.  Some parts use only tabs, other parts use mix tabs/spaces, etc.  That is definitely something that should be standardized.  I propose using the Android Code Formatter and Imports Organizer, since there are config files available for Eclipse, Android Studio, IntelliJ, XCode, and emacs:
https://f-droid.org/forums/topic/proposal-standardize-java-code-format-on-android-settings/

**Comment by devrandom** [comment]
Looks good overall.

**Comment by eighthave** [comment]
@devrandom do you want to merge this when you think its ready? or shall I? Or should we wait for another reviewer?

**Comment by devrandom** [comment]
BTW, I recommend in the future to keep large code movements to their own pull request, for ease of reviewing

**Comment by eighthave** [comment]
Yeah, this is a bit too big, but it was basically all directly related, so I kept it together.  The merging of AuthContext/AuthContextImpl and Session/SessionImpl came about while I was trying to get the tests working.

**Pull request merged**
