### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by languitar**
This pull requests contains several commits that clean up the unit tests wrt. logic and style.

### CODE REVIEW

**Comment by eighthave** [comment]
Can you say a little more about why you made some of these changes? For example, while the junit4 style might be official, it can be a bit odd.  Are there any junit4 features that we need to use?
http://srivaths.blogspot.com/2009/02/junit-3-junit-4-oil-water.html

**Comment by languitar** [comment]
Basically just for the sake of cleaning things up.

A mixture of junit 3 and 4 doesn't help much and just looks like something that never got cleaned up.

The stream should obviously be closed correctly all the time and eclipse with default warnings even complains about this. The same is true for the unused members.

Finally, for the SessionImplTest, using real assertions in contrast to if-fail constructs generates much better failure messages in case one of the assertions fails because junit will then directly report the mismatching values.

**Comment by languitar** [comment]
Oh, was there an update to your comment? Actually I did not introduce the junit 4 dependency nor the use of that style. There was simply a mixture and I tried to unify this. For the SessionImplTest, however, junit4  with the hamcrest core is required to have expressive test assertions since some of the conditions there cannot be expressed with the usual assertXXXX methods.

**Comment by eighthave** [comment]
I didn't realize junit4 style was in use in some places.  Definitely makes sense to use one style throughout.

**Comment by eighthave** [comment]
rebased on master and pushed. 
- c7d123b8f99d382b8fa7284c5239d303ffbe0440
- cdcd2cfa9bb585576652c3d8688282dd7306f093
- b4d6dcf711190036593a21b6ffbe865f9c76627f
- a440c84f825398f979a1eed9d6b0699057b4875b

**Pull request closed without merging**
