### PR TITLE
Enforce consistent coding conventions

### PR DESCRIPTION
**Pull request by languitar**
The current state of the source code is that multiple coding style exist in parallel and a lot of small things differ between individual files. I would really like to clean this up but this obviously requires a discussion about coding conventions that should be used. For this purpose I'd like to used this PR, in case interest exists in this direction.

My rough proposal would be the following:
- Consistently indent with spaces instead of tabs (Indentation will look the same everywhere)
- Convert all line endings to Unix style (this is recommended for/by Git)
- Generally, stay close to the sun java styles, as is currently mostly the case

In order to enforce any style that will come up, I'd propose to include at least checkstyle, optionally PMD in the build process. The first commit in the request introduces checkstyle reporting in maven with a rule set I usually like to work with. You can try this out by calling `mvn site` and then opening `target/site/index.html`. There will be a lot of warnings right now. ;)

### CODE REVIEW

**Comment by eighthave** [comment]
Yes!  The style I propose is documented in #10.  I don't know if there is an Android `checkstyle` config.  The Android code style does match your three bullets.

**Comment by eighthave** [comment]
Before merging this, I'd like to get agreement from others on this.  So I'll ping @cobratbq @devrandom @n8fr8 @a-iv

**Comment by languitar** [comment]
Actually, before merging this, the pull requests should probably clean up the code accordingly as far as possible ;) And I can easily modify the settings of the checkstyle configuration. But to do this, I would need more detailed feedback on the different errors reported there. Not just only the spaces vs. tabs thing.

Along these lines, I would also vote to distribute an eclipse formatter style with the project that matches the style. This usually helps a lot and I suspect that some people are using Eclipse for development. The same should probably be true for netbeans, but I don't use netbeans.

**Comment by devrandom** [comment]
This sounds like a promising direction.  I would need an IntelliJ setting if it doesn't match the existing built-in styles.

**Comment by cobratbq** [comment]
I use both Eclipse and Netbeans. I prefer Netbeans nowadays if possible. I'm wondering whether it isn't better to have some independent formatter. I like consistent formatting, especially if it doesn't take any manual effort. I think, however, that the various formatting engines (Eclipse, Netbeans, IntelliJ, etc.) deviate in behaviour, so depending on the IDE's formatting will cause some trouble. Anyone have a solution for that?

**Comment by languitar** [comment]
I once tried to find decent external formatters but never found anything as complete as the IDE-internal ones. And in any case, people are using IDEs to develop, so they should be able to use the features included in the IDE. Apart from that, most formatters can be customized quite well nowadays and we should be able to come up with configurations that match each other quite well. The last resort will be checkstyle, which will warn in case something is violated. Finally, it should be clear that using the auto formatter blindly for whole files or the whole project on every tiny change will lead to problems nearly in any situation and messes up any patch.

So:
- Checkstyle (and optionally PMD) will be the definitive answer to style questions
- IDE formatters will be configured to match theses guidelines as close as possible (and at least for Eclipse I can say that this very possible)
- Any auto formatter will not help in case people do not know how to create good patches with localized changes ;)

**Comment by eighthave** [comment]
I think we really should try to avoid coming up with a custom code format.  We
should try to use a standard one, so it'll be something that people are
already using.  Even though it is an extra config step, I think that the
Android code formatter is our best bet because there are already configs for
many IDEs, it is quite close to the standard Java format, I think the only
difference is it allows for 100 char lines rather than 80 char lines, and it
forces only spaces for indent while Java format seems to allow tabs or mixed.
Plus, a lot of Android code is formatted using it, and many Android devs
already have it set up.

Also, the Android code style is pretty well documented, including things
beyond just the code format:
https://source.android.com/source/code-style.html

I think that `astyle` can match the detail of the Eclipse code formatter.
`astyle` really has a lot of details, but it would take a little bit of config
to get all the details set and enforced.  But I'm fine using any program that
is included in Debian: astyle and checkstyle are, PMD is not.

**Comment by eighthave** [comment]
@cobratbq in case you missed it, the Android code format is supported in Eclipse, Android Studio, IntelliJ, XCode, and emacs:
https://f-droid.org/forums/topic/proposal-standardize-java-code-format-on-android-settings/

Then having a script that will do it using `astyle` or `checkstyle` will cover the rest.

**Comment by languitar** [comment]
Ok, In case we can agree on the android style, I can try to come up with a project structure that enforces this code style through checkstyle and maybe PMD (which will be integrated with maven and doesn't require any external program).

**Comment by cobratbq** [comment]
I'm fine with that style if that's well supported. I am okay with most styles, as long as I can get decent support from the IDE so that I don't need to think about the style too much. I'll just wait for whatever @languitar cooks up. :+1:

**Comment by languitar** [comment]
Give me a few days to find a good recipe for a magic potion ;)

**Comment by languitar** [comment]
I am currently working on this branch, so there will be changes all the time. This is just work in progress. I will inform you once I think everything is done.

**Comment by languitar** [comment]
Alright, included in this pull request are now configurations for checkstyle and pmd, both integrated with maven. Moreover, There are commits to reformat the whole code base to unix line endings. Since it is hard to keep this commit up to date with the repository, it should be merged quite soon or it needs to be redone.

Reports can be generated with `mvn site`. Please try this out and have a look at the generated warnings. I would propose to split up accepting the checkstyle and PMD rules in this report and the actual reformatting of the source code to adhere to these rules into two requests since and discussion here will results in the reformatting being outdated due to other changes on the master. I can do the reformatting once we agree on the rules.

Moreover, I have a working draft for IDE configurations to match these rules, but aligning them in detail with the rules takes some time and as long as there's a chance that things will be changed in the rules, I did not want to perform all the work to fine-tune the projects. I will create a new pull requests once these configurations are applied.

So, please look at the generated reports and indicate whether you are satisfied with the rulesets or not. The reason for the newline commit being included in this pull request is that there would be one warning in each source code line otherwise. So this one is included to make the reports more readable with respect to that specific issue. There will still be a lot of warnings because the source code style obviously does not match in many places.

The rulesets adhere to the android style guide (which is very open in many senses) apart from once specific aspect: I did not include the prefixing of member variables. This hasn't been done in the source code so far and would mean that we would have to change EVERY variable name in the source code (and even constant names, which severely affects the interface compatibility). Moreover, I personally think that IDEs and syntax highlighting should already do the job of explaining where things come from. ;)

**Comment by cobratbq** [comment]
Hi @languitar, I merged this, since it looks good and, like you said, we should not wait for too long with these kinds of changes. I had to fix some merge conflicts, because I merged eighthave's changes earlier today. Can you do a quick check to ensure that I didn't f*ck up, just in case? :-P (I left the conflicts in the notes of the merge commit.) Thanks.

**Comment by eighthave** [comment]
well, I was hoping to hold off on this one since I have two pull requests open (#16 and #23), and commits like  40692b7 that change every single line of code make rebasing very difficult, and also make keeping in sync with a fork like jitsi/otr4j very difficult.  This really should have waited until the jitsi team was officially on board.  But its done, so hopefully the jitsi team will join us here...  now I am off to struggle with rebasing my pull requests...

**Comment by cobratbq** [comment]
@eighthave I wasn't aware of this, so I'm sorry for rushing this. You could try using a merge tool that's whitespace-aware, as much as of the changes have only to do with line endings and/or spacing. You can probably rebase with little effort to the new code base. I'll try it this evening in a dry-run just to see if that works.

**Comment by eighthave** [comment]
For future reference: there is no rush to commit any of the formatting fixes because they are all reproducibly created by scripts.  We should make sure that everyone is in agreement before committing any more mass formatting fixes.  They are too disruptive to be merged without that level of agreement.

**Comment by cobratbq** [comment]
FWIW, as I understood @languitar 's request, this was supposed to provide a "baseline" for spacing and line endings as well as a decent start for formatting configurations and analysis. I understand that repeatedly merging changes that touch all files will significantly interrupt branch usage. Even so, I still think it is a good thing to establish this "baseline".

Now at least we have a known, common basis in line endings and (checking) configurations.

@eighthave I have tried rebasing https://github.com/otr4j/otr4j/pull/16 and https://github.com/otr4j/otr4j/pull/23 and this works like a charm when using a merge tool. The only conflict I manually resolved was in pom.xml which is indeed modified in 2 different ways. Other than that, everything was merged automatically and at least all unit tests ran successfully afterwards. I have created separate branches for them, just in case you find them useful. You can find the rebased branches at https://github.com/cobratbq/otr4j/tree/rebased-reorg-tlv-handling and https://github.com/cobratbq/otr4j/tree/rebased-random-fixes .

**Comment by languitar** [comment]
Sorry, maybe I can have a look at the changes tomorrow. Spare time is currently limited.

**Comment by eighthave** [comment]
@cobratbq I took your rebased branches for #16 and #23 and pushed them to my pull requests.  They worked for me.  Now if only someone would review them... ;-)

**Pull request merged**
