### PR TITLE
Eliminate unneeded Impl classes

### PR DESCRIPTION
**Pull request by eighthave**
Following up on the work started in #8, this commit eliminates all of the `Impl` classes and merges them into a single class with the paired `interface`.  The `interface`s `Session`, `AuthContext`, `SessionKeys`, `OtrPolicy`, `OtrCryptoEngine` and `OtrSessionManager` were all only ever used in the corresponding `Impl` class.  I checked the code for ChatSecure, Conversations, Jitsi Desktop, Jitsi-Android, and Xabber to make sure these `interface`s were not being used.

The primary reason that I want to do this change is because having them split up like that makes it hard to write tests for those classes.  But it also makes the code base cleaner and smaller.

### CODE REVIEW

**Comment by languitar** [comment]
I don't understand why it is harder to write tests against implementation classes than against normal ones without an interface. Actually, having a well-defined interface should foster writing unit tests since then stubs and mocks can be used much easier. Moreover, one can define interface-level tests that could be used by client projects which potentially implement other versions.

**Comment by languitar** [comment]
Apart from that, I don't see any reason for  bacd468 and 026f6a7 being included in this PR. They have nothing to do with removing Impl classes.

**Comment by eighthave** [comment]
I ended up finding a method to write the tests that probably didn't need the Impl changes, but those internal interfaces were just noise in the code.  They were not used in the code except to be implemented by a single class, and they are not used in any otr4j app that I know of.

I just threw in bacd468 and 026f6a7 because they are tiny, easy to understand fixes.

**Comment by eighthave** [comment]
arg, oops, sorry, got confused there with the git command line, but I fixed it in the repo.  Donno why github still shows this as merged, since git does not.

**Pull request merged**
