### PR TITLE
Simplified fragmenter for otr4j

### PR DESCRIPTION
**Pull request by cobratbq**
A simplification of the otr4j fragmenter. The maximum number of messages instruction is removed because it cannot correctly handle the maximum number of messages for all cases.

The correct method to achieve this is to implement this in the OtrEngineHost instance and the classes that send messages, since those instances can work together with the actual underlying IM protocol to manage the number of messages and imlement its own (protocol-specific) method of stalling for time or extending the number of messages to be allowed to be sent or whichever mechanism works to stay without protocol boundaries.

### CODE REVIEW

**Comment by eighthave** [comment]
I agree it makes sense to leave the "method for stalling for time" outside of otr4j and let the client implement it as related to the underyling protocol.  But if there is already code that implements some form of this stalling, it would be nice to have it in the form of an example and/or test.

**Comment by eighthave** [comment]
Returning a `null Integer` feels odd to me.  How about returning `int`, and if there is no maximum fragment size, return `-1`?

**Comment by languitar** [comment]
Using -1 for a special case sounds worse to me then null. In case people forget to check for the special case, -1 might ripple through subsequent code without being noticed or very strange results, while null will clearly crash and indicate what is wrong.

**Comment by eighthave** [comment]
Having a negative size should be detectable by code that is checking sizes of things, since nothing can ever have a negative size.  I've never seen a method returning an `null Integer`.  There is precedence to returning `-1` size:
- https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html#chunkLength
- https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html#fixedContentLength

**Comment by languitar** [comment]
To me this sounds like anciently keeping up C traditions. There are sooo many bugs out there because people forget to check these return values correctly. I would always vote to avoid such obvious pitfalls. Just because "it can be easily checked" doesn't mean people will remember to do so.

**Comment by languitar** [comment]
Maybe a different proposal. Since the specific case shall reflect "unlimited", why not returning `Integer.MAX_VALUE` in that case?

**Comment by eighthave** [comment]
@languitar instead of making up our own return value API, we should use what similar APIs  already do. I think that's the best insurance against bugs. The `-1` pattern is used in core Java classes.  Do you have any references for your `Integer.MAX_VALUE` proposal?

**Comment by languitar** [comment]
@eighthave how shall bad design ideas phase out in case no one dares to change them? ;)

http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#MAX_VALUE In case this value is returned and not handled specifically, everything will still work correctly. And with an integer, no one will ever be in the position to create a bigger fragment than this.

**Comment by languitar** [comment]
Along these lines the following references:
- http://lcsd05.cs.tamu.edu/slides/keynote.pdf pdf page 36
- http://www.embedded.com/design/prototyping-and-development/4227354/APIdeology--Application-Programming-Interface-best-practices (search for -1)
- http://blog.isnotworking.com/2007/05/api-design-guidelines.html ("Avoid return values that Demand Exceptional Processing")

**Comment by eighthave** [comment]
I'm all for modernizing APIs, but that does not happen by changing one method in one obscure library.  That requires a focused and coordinated effort.  This is a pull request for a "simplified fragmenter".  As for references, I mean references of common Java APIs that use the Integer/null pattern.

**Comment by languitar** [comment]
I don't know any references by heart right now for that.

**Comment by cobratbq** [comment]
I don't know of a reference that uses null/Integer. I don't think that specific case matters that much. I do know 'null' is often used to denote the absence of a value. This is the exact case that I am using it for: If no maximum message size is defined, then use null to indicate as such. (If you want a quote for that, see [this article on the justification for Optional](http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html).)

Why I don't like these "special" values borrowed from type's value range: http://rachelbythebay.com/w/2014/08/19/fork/ . I'm not a C-programmer, but I can imagine this going wrong and I would like to prevent it, if possible. :-P

The best option I know of for this kind of intention is [Java 8's Optional](http://docs.oracle.com/javase/8/docs/api/java/util/Optional.html), although you're effectively only hiding the null then. But I guess it could lead to better code, since you're forced to do some checking before you can use the value.

I'd go with Optional, but I think it isn't backported, so we can't use it yet. We can go with Guava's Optional if you're willing to commit to this dependency. (I wouldn't like to, though. I like keeping it lean if possible.) Another option would be to Implement a simplified version ourselves.

Personally, I'm opposed to using the "special" -1 value. For that matter, I think "special" 0 is more suitable then. Since 0 message size doesn't make sense and that way we don't use the negative integer value space.

I prefer to use either null or Optional (custom-made, I guess) and I want to avoid special values if possible.
My 2 cents, I guess :-)

**Comment by cobratbq** [comment]
@eighthave About this "method of stalling for time". I probably described it a bit vaguely. What I was referring to is specifically to the case of IRC, where there's a limit on the amount of messages one can send in a fixed period of time. I know of some IRC client that prevents trespassing on this limit by delaying sending messages. I don't have an implementation for that that we can use as an example, though.

In essense, it is very simple though. It basically is: instead of blindly following the method call "injectMessage" method call originating from otr4j, now first check if you are allowed to send, then you send. If not, use your method of choice to make it so that you are allowed to send, or fail altogether, or whatever. In any case this must happen outside otr4j, since we do not immediately send encrypted messages, so we can never provide a complete solution inside otr4j.

**Comment by devrandom** [comment]
I believe that MAX_VALUE is the least surprising solution.

With Integer, the caller might not notice that the return value is an Integer rather than an int, and end up crashing when trying to assign a null Integer to an int variable.  I agree that -1 is a C holdover and it can lead to other issues here because it's actually less than all other legal values.

**Comment by cobratbq** [comment]
Keep in mind that otr4j is the caller. The interface needs to be implemented by the host application, such that we can query what our imposed limits are w.r.t. message size.

**Comment by eighthave** [comment]
I'm fine with returning an `int` and setting `Integer.MAX_VALUE` when there is no other limit.  I think `null` could also be misleading since there will always be a limit to the fragment size somewhere.  If the fragment size is held in an `int` or `Integer`, then it will be impossible to have a fragment bigger than `Integer.MAX_VALUE`.  So that seems like the most honest response.

**Comment by cobratbq** [comment]
Okay so I'll go with Integer.MAX_VALUE.

**Comment by cobratbq** [comment]
Changed the dont-need-fragmentation-value to Integer.MAX_VALUE. All tests succeed. Let me know if there's anything else.

**Comment by devrandom** [comment]
Thank you!

**Pull request merged**
