### PR TITLE
Fix SM for non ascii chars.

### PR DESCRIPTION
**Pull request by aelmahmoudy**
I found this commit: redsolution/otr4j@6bf69731dd8b97c4665fa16ab35a382eb9266504 which fixes the issues of using non-latin characters for question/answer and also shared secrets. So I cherrypicked it

### CODE REVIEW

**Comment by aelmahmoudy** [comment]
Yet it still does _NOT_ fix the problem of non-latin OTR encrypted messages (#46)

**Comment by eighthave** [comment]
Are you having problems with non-latin characters in the SMP question/answer?  The tests pass with a wide range of non-latin characters as of now, but if you are having trouble still, then the tests are missing something.  I think there are still troubles with nulls (\0) and carriage returns (\n).

**Comment by aelmahmoudy** [comment]
yes. before applying that commit, if I used arabic characters in SMP Q/A or shared secret the authentication would fail. The test was one user using Xabber (that uses OTR4j), and the other user is on Pidgin

**Comment by aelmahmoudy** [comment]
so ?

**Comment by eighthave** [comment]
sorry, I was at a conference, I'll take a look at this this week

**Comment by eighthave** [comment]
Looking at that commit, I don't think it changes the logic of the code there at all.  And the tests of the SMP question/answer are passing with a wide range of unicode characters, so I don't think this commit is needed.

**Comment by aelmahmoudy** [comment]
again this unicode issue is not a problem with otr4j vs otr4j, yet a problem with otr4j vs libotr

**Comment by eighthave** [comment]
Ok, I understand this commit now.  `secret.length()` is the length of the `String`, but OTR needs to be aware of the length of the actual `byte[]`.  With UTF-8, the length of the string will be different than the number of bytes.

**Comment by aelmahmoudy** [comment]
Thanks ! I hope you find a fix for #46 too

**Comment by eighthave** [comment]
I'm working on it now...  it is not easy for me to reproduce.  I was trying
with ChatSecure, and messages with Unicode came through fine from Pidgin and
Gajim.

**Pull request closed without merging**
